import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { SectionCard, StatusPill } from "@/components/flowcore-ui";
import { checkConnection, ConnectionPreference, ConnectionState, defaultSettings, FlowCoreSettings, loadSettings, saveSettings } from "@/lib/flowcore";

const preferences: Array<{ value: ConnectionPreference; label: string }> = [{ value: "auto", label: "Automático" }, { value: "tailscale", label: "Privado" }, { value: "cloudflare", label: "Público" }];

export default function ConnectionScreen() {
  const [settings, setSettings] = useState<FlowCoreSettings>(defaultSettings);
  const [state, setState] = useState<ConnectionState | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  const test = useCallback(async (nextSettings?: FlowCoreSettings) => { setLoading(true); const status = await checkConnection(nextSettings ?? settings); setState(status); setLoading(false); }, [settings]);
  // eslint-disable-next-line react-hooks/exhaustive-deps -- runs once on mount only; re-running on every `test`
  // reference change (i.e. every keystroke in the fields below) would reload the last saved settings over
  // whatever the user is currently typing, making the inputs look like they reject input.
  useEffect(() => { loadSettings().then((saved) => { setSettings(saved); test(saved); }); }, []);
  const update = (key: keyof FlowCoreSettings, value: string) => setSettings((current) => ({ ...current, [key]: value }));
  const persist = async () => { setSaving(true); await saveSettings(settings); await test(settings); setSaving(false); };

  return <ScreenContainer className="px-4"><View style={styles.content}><Text style={styles.heading}>Conexão</Text><Text style={styles.subtitle}>Cloudflare é o acesso HTTPS público. Tailscale é a rota privada entre dispositivos autorizados.</Text><SectionCard title="Estado atual" accent={state?.reachable ? "#34C38F" : "#F06B6B"}>{loading ? <ActivityIndicator color="#20C6D8" /> : <View style={styles.status}><StatusPill label={state?.reachable ? "Conectado" : "Indisponível"} tone={state?.reachable ? "good" : "bad"} /><Text style={styles.endpoint}>{state?.endpoint || "Nenhum endpoint"}</Text><Text style={styles.meta}>{state?.reachable ? `Via ${state.source} · FlowCore ${state.version ?? ""}` : state?.error ?? "Falha de conexão"}</Text></View>}</SectionCard><SectionCard title="Preferência de rota"><View style={styles.choiceRow}>{preferences.map((item) => <TouchableOpacity key={item.value} onPress={() => setSettings((current) => ({ ...current, preference: item.value }))} style={[styles.choice, settings.preference === item.value && styles.choiceActive]}><Text style={[styles.choiceText, settings.preference === item.value && styles.choiceTextActive]}>{item.label}</Text></TouchableOpacity>)}</View></SectionCard><SectionCard title="Endpoints"><Text style={styles.inputLabel}>Cloudflare público</Text><TextInput value={settings.publicUrl} onChangeText={(value) => update("publicUrl", value)} autoCapitalize="none" autoCorrect={false} keyboardType="url" style={styles.input} placeholderTextColor="#6E86A5" /><Text style={styles.inputLabel}>Tailscale privado</Text><TextInput value={settings.privateUrl} onChangeText={(value) => update("privateUrl", value)} autoCapitalize="none" autoCorrect={false} keyboardType="url" style={styles.input} placeholder="https://nome-do-dispositivo.tailnet.ts.net" placeholderTextColor="#6E86A5" /></SectionCard><TouchableOpacity onPress={persist} disabled={saving} style={[styles.button, saving && styles.buttonDisabled]}><Text style={styles.buttonText}>{saving ? "Testando…" : "Salvar e testar conexão"}</Text></TouchableOpacity><Text style={styles.footnote}>O aplicativo não guarda token do Cloudflare nem credencial do Tailscale. Somente URLs de endpoints autorizados são armazenadas localmente.</Text></View></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { paddingVertical: 16, gap: 14 }, heading: { color: "#EAF2FB", fontSize: 30, lineHeight: 36, fontWeight: "800" }, subtitle: { color: "#9CB0C9", fontSize: 14, lineHeight: 20 }, status: { gap: 8 }, endpoint: { color: "#EAF2FB", fontSize: 14, lineHeight: 20, fontWeight: "700" }, meta: { color: "#9CB0C9", fontSize: 12, lineHeight: 18 }, choiceRow: { flexDirection: "row", gap: 8 }, choice: { flex: 1, borderWidth: 1, borderColor: "#223A58", backgroundColor: "#0E1A2A", borderRadius: 12, paddingVertical: 10, alignItems: "center" }, choiceActive: { borderColor: "#20C6D8", backgroundColor: "#123247" }, choiceText: { color: "#9CB0C9", fontSize: 12, lineHeight: 16, fontWeight: "700" }, choiceTextActive: { color: "#20C6D8" }, inputLabel: { color: "#9CB0C9", fontSize: 12, lineHeight: 16, fontWeight: "700", marginTop: 6, marginBottom: 5 }, input: { color: "#EAF2FB", fontSize: 13, lineHeight: 19, borderColor: "#223A58", borderWidth: 1, borderRadius: 12, backgroundColor: "#0E1A2A", paddingHorizontal: 12, paddingVertical: 11 }, button: { minHeight: 48, backgroundColor: "#20C6D8", borderRadius: 14, alignItems: "center", justifyContent: "center" }, buttonDisabled: { opacity: 0.6 }, buttonText: { color: "#08111F", fontSize: 15, lineHeight: 20, fontWeight: "800" }, footnote: { color: "#7893B5", fontSize: 12, lineHeight: 18, textAlign: "center", paddingHorizontal: 10 } });
