import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, FlatList, RefreshControl, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { EmptyState, SectionCard, StatusPill } from "@/components/flowcore-ui";
import { checkConnection, formatDelta, formatNumber, getMarketOverview, MarketItem, MarketOverview } from "@/lib/flowcore";

function MiniMarketCard({ item }: { item: MarketItem }) { const positive = (item.delta_pct_1d ?? 0) >= 0; return <View style={styles.mini}><Text style={styles.miniSymbol}>{item.symbol}</Text><Text style={styles.miniLevel}>{formatNumber(item.level)}</Text><Text style={[styles.miniDelta, { color: positive ? "#34C38F" : "#F06B6B" }]}>{formatDelta(item.delta_pct_1d)}</Text></View>; }

export default function HomeScreen() {
  const router = useRouter();
  const [market, setMarket] = useState<MarketOverview | null>(null);
  const [online, setOnline] = useState<boolean | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setError(null); try { const [connection, overview] = await Promise.all([checkConnection(), getMarketOverview()]); setOnline(connection.reachable); setMarket(overview.data); } catch (e) { setOnline(false); setError(e instanceof Error ? e.message : "Não foi possível atualizar o FlowCore"); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const preview = market?.items.slice(0, 6) ?? [];
  return <ScreenContainer className="px-4"><FlatList data={preview} numColumns={2} keyExtractor={(item) => item.symbol} renderItem={({ item }) => <MiniMarketCard item={item} />} columnWrapperStyle={preview.length ? styles.gridRow : undefined} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} tintColor="#20C6D8" />} ListHeaderComponent={<View style={styles.header}><View style={styles.brandRow}><View><Text style={styles.brand}>FlowCore</Text><Text style={styles.brandCaption}>Mercado, carteira e IA em um só fluxo</Text></View><StatusPill label={online ? "Online" : "Offline"} tone={online ? "good" : "bad"} /></View><SectionCard title="Leitura diária"><Text style={styles.h1}>Decisão informada, não automática.</Text><Text style={styles.copy}>O app mostra o mesmo fluxo de dados que alimenta o briefing de mercado e mantém as decisões de investimento sob aprovação humana.</Text><View style={styles.actions}><TouchableOpacity style={styles.primary} onPress={() => router.push("/(tabs)/market")}><Text style={styles.primaryText}>Abrir mercado</Text></TouchableOpacity></View></SectionCard><View style={styles.sectionHeader}><Text style={styles.sectionTitle}>Mercado agora</Text><TouchableOpacity onPress={() => router.push("/(tabs)/market")}><Text style={styles.link}>Ver tudo</Text></TouchableOpacity></View></View>} ListFooterComponent={preview.length ? <SectionCard title="Alertas"><View style={styles.alerts}>{market?.alerts?.length ? market.alerts.slice(0, 3).map((alert, index) => <View key={`${alert.label}-${index}`} style={styles.alert}><StatusPill label={alert.severity} tone="warning" /><Text style={styles.alertText}>{alert.label}</Text></View>) : <Text style={styles.emptyText}>Nenhum alerta ativo retornado pela API.</Text>}</View></SectionCard> : null} ListEmptyComponent={loading ? <ActivityIndicator color="#20C6D8" /> : (error && !online ? <EmptyState title="Sem conexão" detail="Verifique sua conexão com FlowCore." /> : null)} contentContainerStyle={styles.content} /></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { paddingVertical: 16, gap: 10 }, header: { gap: 14, marginBottom: 4 }, brandRow: { flexDirection: "row", justifyContent: "space-between", gap: 16, alignItems: "center" }, brand: { color: "#EAF2FB", fontSize: 30, lineHeight: 36, fontWeight: "800" }, brandCaption: { color: "#9CB0C9", fontSize: 13, lineHeight: 19, marginTop: 2 }, h1: { color: "#EAF2FB", fontSize: 22, lineHeight: 28, fontWeight: "800" }, copy: { color: "#B8CAE0", fontSize: 14, lineHeight: 21, marginTop: 7 }, actions: { flexDirection: "row", gap: 9, marginTop: 16 }, primary: { flex: 1, backgroundColor: "#20C6D8", borderRadius: 12, minHeight: 44, alignItems: "center", justifyContent: "center" }, primaryText: { color: "#08111F", fontSize: 14, lineHeight: 18, fontWeight: "800" }, sectionHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, sectionTitle: { color: "#9CB0C9", fontSize: 12, lineHeight: 16, letterSpacing: 0.8, textTransform: "uppercase", fontWeight: "700" }, link: { color: "#20C6D8", fontSize: 13, lineHeight: 18, fontWeight: "700" }, gridRow: { gap: 10 }, mini: { flex: 1, minHeight: 102, backgroundColor: "#122033", borderColor: "#223A58", borderWidth: 1, borderRadius: 14, padding: 13, marginBottom: 10 }, miniSymbol: { color: "#9CB0C9", fontSize: 12, lineHeight: 16, fontWeight: "700" }, miniLevel: { color: "#EAF2FB", fontSize: 18, lineHeight: 24, fontWeight: "800", marginTop: 5 }, miniDelta: { fontSize: 12, lineHeight: 17, fontWeight: "700", marginTop: 2 }, alerts: { gap: 9 }, alert: { flexDirection: "row", alignItems: "center", gap: 8 }, alertText: { color: "#D7E5F4", fontSize: 13, lineHeight: 19, flex: 1 }, emptyText: { color: "#9CB0C9", fontSize: 13, lineHeight: 19 } });
